# 47장 에러처리

## 47.1 에러 처리의 필요성
- 에러에 대한 대처를 하지 않고 방치하면 프로그램은 강제 종료된다.  
- 프로그램의 강제 종료를 막을 방법에는 크게 `try...catch`문 옵셔널 체이닝 연산자`?.` 가있다. 

## 47.2 try...catch...finally문
```js
try{
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // 에러가 발생하면 이 코드블록의 코드가 실행
  // err에는 try에서 발생한 error객체가 전달된다.
} finally {
  // 에러 발생 여부와 상관없이 반드시 한 번 실행된다.
}
```

## 47.3 Error객체
Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.
```js
const error = new Error('invalid')
```
|생성자 함수|인스턴스|
|---|---|
|Error|일반적인 에러 객체|
|SyntaxError|JS 문법에 맞지 않는 문을 해석할 때 발생하는 객체|
|ReferenceError|참조할수 없는 식별자를 참조했을때 발생하는 에러 객체|
|TypeError|피연산자 또는 이눗의 데이터 타입이 유효하지 않을때 발생하는 에러 객체|
|RangeError|숫자값의 허용범위를 벗어났을 대 발생하는 에러 객체|
|URIError|encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체|
|EvalError|eval 함수에서 발생하는 에러 객체|

## 47.4 throw문
Error 생성자 함수로 에러 객체가 생성되고 에러가 발생하는 것이 아니다.  
에러를 발생시키기 위해서는 try 코드 블록에서 throw문으로 에러 객체를 던져야한다.  
```js
try{
  throw new Error('wrong')
}catch(err){
  console.log(err)
}
```

## 47.5 에러의 전파
에러는 호출자 방향으로 전파된다. 

```js
const foo = () => {
  throw Error('error발생!')
}

const bar = () => {
  foo()
}

try {
  bar()
}catch(err){
  console.log(err) // error 발생
}
```
